### model
model_name_or_path: unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit


### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: sol4_train
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/qwen
logging_steps: 25
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 6
learning_rate: 0.000005
num_train_epochs: 30
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.2
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 250

# logger

report_to: wandb
run_name: qwen2.5-3B
